### ISSUE TITLE
ANativeActivity_onCreate not found: undefined symbol: ANativeActivity_onCreate

### ISSUE THREAD

**Issue by epVladimir** [4rcz3r/SFML-Android-Template#1]
Hi 4rcz3r
I followed all the steps that you wrote in your "Tutorial: Building SFML for Android on Windows with Android Studio" tutorial, but I faced an issue. And I have not been able to solve it.

SO
--
- Win 10

Environment
--
- Android Studio Dolphin | 2021.3.1 Patch 1
- buildToolsVersion '33.0.0'
- ndkVersion '25.1.8937393'
- compileSdk 33
- cmake "3.24.3"

SFML was built for the following architectures
--
- armeabi-v7a
- x86
- arm64-v8a
- x86_64 
And they were successfully installed in the NDK third-party directory.

Tests
--
- Real device (API 29)
- Emulator (API 30)
- Emulator (API 28)

Error
--
```
2022-12-23 22:06:11.089 11470-11470/? I/u.example.debu: Late-enabling -Xcheck:jni
2022-12-23 22:06:11.100 11470-11470/? W/u.example.debu: Unexpected CPU variant for X86 using defaults: x86
2022-12-23 22:06:11.330 11470-11470/com.you.example.debug W/u.example.debu: Accessing hidden field Landroid/os/Trace;->TRACE_TAG_APP:J (light greylist, reflection)
2022-12-23 22:06:11.330 11470-11470/com.you.example.debug W/u.example.debu: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (light greylist, reflection)
2022-12-23 22:06:11.359 11470-11470/com.you.example.debug W/NativeActivity: ANativeActivity_onCreate not found: undefined symbol: ANativeActivity_onCreate
2022-12-23 22:06:11.359 11470-11470/com.you.example.debug D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2022-12-23 22:06:11.360 11470-11470/com.you.example.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.you.example.debug, PID: 11470
    java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/com.you.example.debug-MOi3Rg7kIzBCbHicjVcyMg==/lib/x86/libsfml-activity-d.so": undefined symbol: ANativeActivity_onCreate
        at android.app.NativeActivity.onCreate(NativeActivity.java:175)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2022-12-23 22:06:11.365 11470-11470/com.you.example.debug I/Process: Sending signal. PID: 11470 SIG: 9
```

I hope you can help me with this

**Comment by 4rcz3r** [comment]
Hi, it looks that it's linking error.
Could you see content of your apk's lib/x86 folder (Build->Analyze APK) and check if libsfml-activity-d.so is there?
Maybe you are using different SFML version than that in CMakeLists.txt. If it isn't there, take a look into CMakeLists.txt. and try to follow my comments there.

**Comment by epVladimir** [comment]
Hi again,
This is the content of the APK
![apkcontent](https://user-images.githubusercontent.com/89207242/209492286-69b71c74-4b84-4cc1-a2f4-8873ac098507.jpg)
As we can see the lib is there.
And when I built the SFML, I used the master branch which is version 3.

**Comment by 4rcz3r** [comment]
At the moment I have SFML 2.6.x installed but if CMakeLists.txt is ok I think it shouldn't matter (?). I installed emulator x86 with API 28 and for me that project works. Could try installing that app [4rcz3r-app-x86-debug.zip](https://github.com/4rcz3r/SFML-Android-Template/files/10302455/4rcz3r-app-x86-debug.zip) on your emulator and tell me if it works? Or maybe you could send me your app to test?
I could also install latest SFML to check if they changed something because if you use all files from my template then idk what else I can do for you.

**Comment by epVladimir** [comment]
I ran the apk that you shared, and it works well

![appSFML](https://user-images.githubusercontent.com/89207242/209612640-3f152058-5b04-49b6-b7f6-b8bdb4254f5b.jpg)

And this is the project, which is your template

https://github.com/epVladimir/sfml_project

I will be trying to figure out what is going on
